# Generated by Django 2.1.2 on 2018-10-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_spoc',
        ),
    ]
