# Generated by Django 2.1.2 on 2018-11-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='profile.png', upload_to='img'),
        ),
    ]
