# Generated by Django 2.1.2 on 2018-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181107_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mydocs/', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('alp', 'Alappuzha'), ('ekm', 'Ernakulam'), ('idk', 'Idukki'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('kol', 'Kollam'), ('ktm', 'Kottayam'), ('koz', 'Kozhikode'), ('mpm', 'Malappuram'), ('pkd', 'Palakkad'), ('ptm', 'Pathanamthitta'), ('tvm', 'Thiruvananthapuram'), ('tcr', 'Thrissur'), ('wnd', 'Wayanad')], max_length=15)),
                ('position', models.CharField(choices=[('Director', 'Director'), ('Chairman', 'Chairman'), ('Associate Director', 'Associate Director'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Member', 'Member')], max_length=15)),
                ('invigilation', models.CharField(max_length=250, verbose_name='Invigilation ')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('organisation', models.CharField(max_length=250, verbose_name='Organization / Institution')),
                ('department', models.CharField(max_length=250, verbose_name='Department ')),
                ('address', models.TextField()),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
