# Generated by Django 2.1.2 on 2018-11-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181120_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='u_date',
            field=models.DateTimeField(),
        ),
    ]
