# Generated by Django 2.1.2 on 2018-11-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_document_u_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rank',
            field=models.IntegerField(default=100),
        ),
    ]
