# Generated by Django 2.1.2 on 2018-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_member_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=70)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
    ]
