# Generated by Django 2.1.2 on 2018-11-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('venue', models.CharField(max_length=70)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('district', models.CharField(choices=[('alp', 'Alappuzha'), ('ekm', 'Ernakulam'), ('idk', 'Idukki'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('kol', 'Kollam'), ('ktm', 'Kottayam'), ('koz', 'Kozhikode'), ('mpm', 'Malappuram'), ('pkd', 'Palakkad'), ('ptm', 'Pathanamthitta'), ('tvm', 'Thiruvananthapuram'), ('tcr', 'Thrissur'), ('wnd', 'Wayanad')], max_length=15)),
                ('sdate', models.DateTimeField()),
                ('info', models.TextField()),
                ('fdate', models.DateField()),
                ('wtype', models.CharField(choices=[('Workshops', 'Workshops'), ('Conferences', 'Conferences'), ('Seminars', 'Seminars')], max_length=15)),
            ],
        ),
    ]
