# Generated by Django 2.1.2 on 2018-11-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('img', models.ImageField(default='download.jpeg', upload_to='gallery')),
                ('status', models.BooleanField(default=True, verbose_name='Approve')),
                ('g_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
